/** Scoped styles use Harness theme tokens in both dark and light appearances. */
export const styles = `
.atn-trigger{display:inline-flex;align-items:center;gap:5px;min-height:28px;padding:3px 7px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-tertiary);font-size:12px;cursor:pointer;white-space:nowrap}
.atn-trigger:hover,.atn-trigger:focus-visible{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2)}
.atn-modal.atn-modal{width:min(1380px,100%);max-height:100%;padding:0;gap:0}
.atn-shell{display:flex;flex-direction:column;min-height:0;max-height:calc(100vh - 96px);color:var(--dsw-alias-label-primary);font-family:inherit;font-size:13px}
.atn-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:20px 24px 15px;border-bottom:1px solid var(--dsw-alias-border-l1)}
.atn-heading{display:flex;align-items:center;gap:9px}.atn-heading h2{font-size:18px;line-height:26px;margin:0;font-weight:600}.atn-head p{margin:6px 0 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.6}
.atn-close,.atn-control{display:inline-flex;align-items:center;justify-content:center;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;min-height:28px;padding:4px 9px;font:inherit}
.atn-close{width:30px;flex:none;font-size:20px;padding:0}.atn-control:hover,.atn-close:hover{background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary)}
.atn-control:focus-visible,.atn-close:focus-visible,.atn-link:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}
.atn-chip{display:inline-flex;align-items:center;gap:5px;white-space:nowrap;border-radius:5px;padding:3px 6px;font-size:11px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary)}
.atn-live{color:var(--dsw-alias-state-success-primary)}.atn-warning{color:var(--dsw-alias-state-warn-label)}.atn-error{color:var(--dsw-alias-state-error-primary)}
.atn-dot{height:6px;width:6px;border-radius:50%;display:inline-block;background:currentColor;flex:none}
.atn-scroll{overflow:auto;min-height:0;overscroll-behavior:contain}.atn-overview{padding:14px 24px;border-bottom:1px solid var(--dsw-alias-border-l1);display:flex;gap:24px;align-items:center}.atn-metrics{display:flex;gap:22px;flex:none}.atn-metric strong{font-weight:600;font-size:23px;line-height:1.2;display:block;font-variant-numeric:tabular-nums}.atn-metric span{display:block;color:var(--dsw-alias-label-secondary);font-size:11px;margin-top:4px}
.atn-goal{min-width:0;flex:1;border-left:1px solid var(--dsw-alias-border-l1);padding-left:22px}.atn-goal small{color:var(--dsw-alias-label-tertiary)}.atn-goal p{margin:5px 0;line-height:1.5;max-height:3em;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}
.atn-main{display:grid;grid-template-columns:minmax(0,1fr) 320px;min-height:440px}.atn-graph-area{min-width:0;display:flex;flex-direction:column}.atn-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 16px;flex-wrap:wrap}.atn-toolbar label{display:flex;align-items:center;gap:6px;color:var(--dsw-alias-label-secondary);font-size:12px}.atn-toolbar input{accent-color:var(--dsw-alias-state-business-primary)}.atn-tools{display:flex;gap:5px}
.atn-canvas{width:100%;height:430px;display:block;background:var(--dsw-alias-bg-layer-1)}.atn-edge{stroke:var(--dsw-alias-state-business-primary);stroke-width:1.5;opacity:.55}.atn-edge-birth{stroke:var(--dsw-alias-label-tertiary);stroke-dasharray:5 5;stroke-width:1;opacity:.5}.atn-edge-selected{opacity:1;stroke-width:2.5}.atn-edge-faded{opacity:.12}.atn-arrow{fill:var(--dsw-alias-state-business-primary)}.atn-arrow-birth{fill:var(--dsw-alias-label-tertiary)}
.atn-node{cursor:pointer;outline:none}.atn-node-ring{fill:var(--dsw-alias-bg-layer-2);stroke:var(--dsw-alias-border-l2);stroke-width:1.5}.atn-node-running .atn-node-ring{stroke:var(--dsw-alias-state-success-primary);stroke-width:2}.atn-node-failed .atn-node-ring{stroke:var(--dsw-alias-state-error-primary)}.atn-node-selected .atn-node-ring,.atn-node:focus-visible .atn-node-ring{stroke:var(--dsw-alias-state-business-primary);stroke-width:3}.atn-node-retired{opacity:.55}.atn-node text{fill:var(--dsw-alias-label-primary);font-size:12px;text-anchor:middle;pointer-events:none}.atn-node .atn-node-status{fill:var(--dsw-alias-label-secondary);font-size:10px}.atn-node-dot{fill:var(--dsw-alias-label-tertiary)}.atn-node-running .atn-node-dot{fill:var(--dsw-alias-state-success-primary)}.atn-node-failed .atn-node-dot{fill:var(--dsw-alias-state-error-primary)}.atn-node-icon{stroke:var(--dsw-alias-label-secondary);fill:none;stroke-width:1.5}
.atn-legend{padding:10px 16px;display:flex;align-items:center;gap:14px;flex-wrap:wrap;color:var(--dsw-alias-label-tertiary);font-size:11px}.atn-legend span{display:inline-flex;align-items:center;gap:5px}.atn-legend-line{width:20px;border-top:2px solid var(--dsw-alias-state-business-primary)}.atn-legend-birth{border-top:1px dashed var(--dsw-alias-label-tertiary)}.atn-graph-help{margin:0;padding:0 16px 12px;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:1.5}
.atn-details{border-left:1px solid var(--dsw-alias-border-l1);padding:16px;max-height:548px;overflow:auto}.atn-section-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 0 12px;font-size:13px;font-weight:600}.atn-node-title{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-bottom:10px}.atn-node-title strong{font-size:16px}.atn-facts{margin:0}.atn-facts div{display:grid;grid-template-columns:78px minmax(0,1fr);gap:10px;margin:8px 0;line-height:1.5}.atn-facts dt{color:var(--dsw-alias-label-tertiary)}.atn-facts dd{margin:0;overflow-wrap:anywhere}.atn-code{font-family:ui-monospace,monospace;font-size:11px}.atn-neighbors{border-top:1px solid var(--dsw-alias-border-l1);padding-top:12px;margin-top:14px}.atn-neighbors h4{font-size:12px;font-weight:500;margin:0 0 7px}.atn-neighbor-list{display:flex;flex-wrap:wrap;gap:5px}.atn-link{border:1px solid var(--dsw-alias-border-l1);background:transparent;color:var(--dsw-alias-state-business-primary);border-radius:5px;padding:3px 6px;cursor:pointer;font:inherit;font-size:11px}.atn-muted{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.6}.atn-task{border:1px solid var(--dsw-alias-border-l1);padding:10px;border-radius:8px;margin-top:8px}.atn-task-head{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:11px}.atn-task p{font-size:12px;line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere;margin:7px 0}.atn-task small{color:var(--dsw-alias-label-tertiary);font-size:10px}.atn-task-result{padding-top:6px;border-top:1px solid var(--dsw-alias-border-l1)}
.atn-feed{padding:16px 24px;border-top:1px solid var(--dsw-alias-border-l1)}.atn-feed-list{max-height:185px;overflow:auto;list-style:none;padding:0;margin:0}.atn-event{display:grid;grid-template-columns:58px 85px minmax(0,1fr);gap:12px;padding:8px 0;border-bottom:1px solid var(--dsw-alias-border-l1);align-items:start;line-height:1.5;font-size:12px}.atn-event time{color:var(--dsw-alias-label-tertiary);font-size:10px;font-variant-numeric:tabular-nums}.atn-event-kind{color:var(--dsw-alias-label-secondary);overflow-wrap:anywhere;font-size:10px}.atn-event-body{min-width:0;overflow-wrap:anywhere;white-space:pre-wrap}.atn-event-body .atn-link{padding:0;border:0;margin-right:6px}.atn-foot{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;padding:10px 24px;border-top:1px solid var(--dsw-alias-border-l1);color:var(--dsw-alias-label-tertiary);font-size:10px}.atn-foot-status{display:flex;align-items:center;gap:8px}.atn-empty{padding:64px 24px;text-align:center;min-height:180px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px}.atn-empty h3{font-size:16px;margin:0;font-weight:500}.atn-empty p{max-width:440px;margin:0;color:var(--dsw-alias-label-secondary);line-height:1.7;font-size:12px}.atn-error-banner{display:flex;align-items:center;gap:10px;padding:9px 24px;font-size:12px;color:var(--dsw-alias-state-warn-label);background:var(--dsw-alias-state-warn-tertiary)}
@media(max-width:950px){.atn-main{grid-template-columns:minmax(0,1fr) 275px}.atn-metrics{gap:14px}.atn-overview{gap:14px}.atn-metric strong{font-size:20px}.atn-goal{padding-left:14px}.atn-canvas{height:390px}}
@media(max-width:720px){.atn-head,.atn-overview,.atn-feed{padding-left:16px;padding-right:16px}.atn-overview{flex-direction:column;align-items:stretch}.atn-metrics{justify-content:space-between}.atn-goal{border-left:0;border-top:1px solid var(--dsw-alias-border-l1);padding:10px 0 0}.atn-main{display:block}.atn-details{border-left:0;border-top:1px solid var(--dsw-alias-border-l1);max-height:320px}.atn-canvas{height:330px}.atn-event{grid-template-columns:52px minmax(0,1fr)}.atn-event-kind{display:none}.atn-shell{max-height:calc(100vh - 70px)}}
@container(max-width:530px){.atn-trigger-label{display:none}}
`
